In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [6]:
#1

""" Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables. """

#Answer

""" array list is an Numpy array which facilitate advanced mathematical and other types of operations on large numbers of data. 
Typically, such operations are executed more efficiently and with less code than is possible using Pythons built-in sequences.
list is the default sequensing object in python where array is only used througgh numpy module
"""

print(type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
#2

""" Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list. """

#Answers

for x in list_:
    print(type(x))
print()

for x in array_list:
    print(type(x))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
#3

""" Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list. """

#Answer

""" data type is changed from string to int in the numpy array"""

array_list = np.array(object = list_, dtype = int)

for x in list_:
    print(type(x))
print()

for x in array_list:
    print(type(x))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [15]:
#4

"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size """

#Answers

print(num_array.shape) # Returns the dimensions of the array
print(num_array.size)  # Returns the number of elements in the array

(2, 3)
6


In [16]:
#5

""" Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]"""

#Answers

z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
#6

""" Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]"""

#Answers

i=np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
